# Inspect Data

In [4]:
import pandas as pd

case_8 = pd.read_csv("data/case_8.csv")

y = case_8.target.values

case_8.drop(["ID","target","v22"], axis=1, inplace=True)

In [5]:
print(case_8.shape)
case_8.head()

(114321, 130)

,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,...,v122,v123,v124,v125,v126,v127,v128,v129,v130,v131
0,1.335739,8.727474,C,3.921026,7.915266,2.599278,3.176895,0.012941,9.999999,0.503281,...,8.000000,1.989780,0.035754,AU,1.804126,3.113719,2.024285,0,0.636365,2.857144
1,1.630686,7.464411,C,4.145098,9.191265,2.436402,2.483921,2.301630,9.031859,1.312910,...,6.822439,3.549938,0.598896,AF,1.672658,3.239542,1.957825,0,1.925763,1.739389
2,0.943877,5.310079,C,4.410969,5.326159,3.979592,3.928571,0.019645,12.666667,0.765864,...,9.333333,2.477596,0.013452,AE,1.773709,3.922193,1.120468,2,0.883118,1.176472
3,0.797415,8.304757,C,4.225930,11.627438,2.097700,1.987549,0.171947,8.965516,6.542669,...,7.018256,1.812795,0.002267,CJ,1.415230,2.954381,1.990847,1,1.677108,1.034483
4,1.630686,7.464411,C,4.145098,8.742359,2.436402,2.483921,1.496569,9.031859,1.050328,...,6.822439,3.549938,0.919812,Z,1.672658,3.239542,2.030373,0,1.925763,1.739389

### One-Hot Encode Objects

In [14]:
cols = case_8.dtypes
display(case_8.loc[:,cols == "object"])
columns = case_8.loc[:,cols == "object"].columns

,v3,v24,v30,v31,v47,v52,v56,v66,v71,v74,v75,v79,v91,v107,v110,v112,v113,v125
0,C,C,C,A,C,G,DI,C,F,B,D,E,A,E,B,O,G,AU
1,C,C,C,A,E,G,DY,A,F,B,D,D,B,B,A,U,G,AF
2,C,E,C,A,C,F,AS,A,B,B,B,E,G,C,B,S,G,AE
3,C,D,C,B,C,H,BW,A,F,B,D,B,B,B,B,J,G,CJ
4,C,E,C,A,I,H,BW,C,F,B,D,C,G,C,A,T,G,Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114316,C,E,C,A,I,E,N,A,B,B,B,C,A,E,A,U,G,AL
114317,C,D,C,B,C,I,BW,A,F,B,D,B,G,C,B,J,G,E
114318,C,A,C,B,C,D,BW,A,B,B,B,B,G,C,B,R,G,Q
114319,C,D,G,A,C,J,AS,A,F,B,D,E,A,E,B,A,G,BW
114320,C,C,C,A,C,G,DA,C,F,B,D,E,F,A,B,A,G,V

In [7]:
from tqdm import tqdm

data = [ pd.get_dummies(case_8[col], prefix=col).copy() for col in tqdm(columns) ]
one_hot_df = pd.concat(data, axis=1)

display(one_hot_df.head())

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 18/18 [00:00<00:00, 77.48it/s]

,v3_A,v3_B,v3_C,v24_A,v24_B,v24_C,v24_D,v24_E,v30_A,v30_B,...,v125_Q,v125_R,v125_S,v125_T,v125_U,v125_V,v125_W,v125_X,v125_Y,v125_Z
0,0,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1

In [8]:
#Drop old columns
case_8_ = case_8.drop(columns, axis=1)

case_8_final = pd.concat([case_8_, one_hot_df], axis=1)
case_8_ = None #take out of memory

print(case_8_final.shape)
display(case_8_final.head())

(114321, 476)

,v1,v2,v4,v5,v6,v7,v8,v9,v10,v11,...,v125_Q,v125_R,v125_S,v125_T,v125_U,v125_V,v125_W,v125_X,v125_Y,v125_Z
0,1.335739,8.727474,3.921026,7.915266,2.599278,3.176895,0.012941,9.999999,0.503281,16.434108,...,0,0,0,0,0,0,0,0,0,0
1,1.630686,7.464411,4.145098,9.191265,2.436402,2.483921,2.301630,9.031859,1.312910,15.447413,...,0,0,0,0,0,0,0,0,0,0
2,0.943877,5.310079,4.410969,5.326159,3.979592,3.928571,0.019645,12.666667,0.765864,14.756098,...,0,0,0,0,0,0,0,0,0,0
3,0.797415,8.304757,4.225930,11.627438,2.097700,1.987549,0.171947,8.965516,6.542669,16.347483,...,0,0,0,0,0,0,0,0,0,0
4,1.630686,7.464411,4.145098,8.742359,2.436402,2.483921,1.496569,9.031859,1.050328,15.447413,...,0,0,0,0,0,0,0,0,0,1

# Remove Highly Correlated Values

Probably should do some EDA too

In [9]:
import numpy as np
def reduce_features(df, verbose = False):
    # calculate the correlation matrix
    corr_matrix  = df.corr().abs()

    # Select upper triangle of correlation matrix
    upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))

    # Find index of feature columns with correlation greater than 0.95
    to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]
    
    #Get all of the correlation values > 95%
    x = np.where(upper > 0.95)

    #Display all field combinations with > 95% correlation
    cf = pd.DataFrame()
    cf['Field1'] = upper.columns[x[1]]
    cf['Field2'] = upper.index[x[0]]

    #Get the correlation values for every field combination. (There must be a more pythonic way to do this!)
    corr = [0] * len(cf)
    for i in range(0, len(cf)):
        corr[i] =  upper[cf['Field1'][i]][cf['Field2'][i]] 

    cf['Correlation'] = corr

    if( verbose ):
        print('There are ', str(len(cf['Field1'])), ' field correlations > 95%.')
        display(cf)
        
        print('Dropping the following ', str(len(to_drop)), ' highly correlated fields.')
        to_drop
        
    #Check columns before drop 
    if( verbose ):
        print('\r\n*********Before: Dropping Highly Correlated Fields*************************************')
        display(df.info(verbose=False))

    # Drop the highly correlated features from our training data 
    df = df.drop(to_drop, axis=1)

    #Check columns after drop 
    if( verbose ):
        print('\r\n*********After: Dropping Highly Correlated Fields**************************************')
        df.info(verbose=False)
    
    return df

In [10]:
%%time

import pickle

case_8_reduced_feats = reduce_features(case_8_final, True)

with open("data\case_8_final_feats.pkl","wb") as f:
    pickle.dump((y, case_8_reduced_feats), f)

There are  46  field correlations > 95%.

     Field1  Field2  Correlation
0       v46      v8     0.975192
1       v63      v8     0.975974
2       v53     v11     0.955757
3       v64     v17     0.982626
4       v76     v17     0.992671
5       v46     v25     0.982215
6       v54     v25     0.967925
7       v63     v25     0.981040
8       v89     v25     0.964606
9      v105     v25     0.962163
10      v60     v26     0.980747
11      v96     v29     0.957029
12      v83     v33     0.964302
13     v114     v40     0.966351
14      v96     v41     0.950463
15     v116     v43     0.977874
16      v63     v46     0.991609
17      v64     v48     0.962521
18     v106     v48     0.980726
19      v89     v54     0.956307
20     v100     v58     0.997665
21      v76     v64     0.953863
22     v115     v69     0.993691
23     v121     v83     0.965987
24      v95     v92     0.977089
25     v118     v97     0.962461
26     v128    v108     0.957299
27    v79_R   v47_B     1.000000
28   v110_B   v47_C     0.999982
29   v110_C   v47_D     0.991951
30    v79_D   v47_E     0.999901
31    v79_K   v47_F     0.998316
32    v79_M   v47_G     1.000000
33   v56_AX   v47_H     1.000000
34    v75_B   v71_F     0.999282
35    v75_D   v71_F     0.999825
36    v74_C   v74_B     0.969791
37    v75_D   v75_B     0.999185
38   v107_E   v91_A     1.000000
39   v107_B   v91_B     1.000000
40   v107_D   v91_C     1.000000
41   v107_G   v91_D     1.000000
42   v107_F   v91_E     1.000000
43   v107_A   v91_F     1.000000
44   v107_C   v91_G     1.000000
45  v125_AE  v112_S     1.000000

Dropping the following  38  highly correlated fields.

*********Before: Dropping Highly Correlated Fields*************************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114321 entries, 0 to 114320
Columns: 476 entries, v1 to v125_Z
dtypes: float64(108), int64(4), uint8(364)
memory usage: 137.4 MB

None

*********After: Dropping Highly Correlated Fields**************************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114321 entries, 0 to 114320
Columns: 438 entries, v1 to v125_Z
dtypes: float64(88), int64(4), uint8(346)
memory usage: 118.0 MB
CPU times: user 42.5 s, sys: 510 ms, total: 43.1 s
Wall time: 43.3 s

# Review Scale

In [ ]:
import pickle

with open("data\case_8_final_feats.pkl","rb") as f:
    y, case_8_reduced_feats = pickle.load(f)
    
columns = case_8_reduced_feats.columns
#Assume values with _ is an object
columns = [ col for col in columns if "_" not in col ]

In [31]:
case_8_reduced_feats[columns].describe()

,v1,v2,v4,v5,v6,v7,v8,v9,v10,v11,...,v119,v120,v122,v123,v124,v126,v127,v129,v130,v131
count,1.143210e+05,1.143210e+05,1.143210e+05,1.143210e+05,1.143210e+05,1.143210e+05,1.143210e+05,1.143210e+05,1.143210e+05,1.143210e+05,...,1.143210e+05,1.143210e+05,1.143210e+05,114321.000000,1.143210e+05,1.143210e+05,1.143210e+05,114321.000000,1.143210e+05,1.143210e+05
mean,1.630686e+00,7.464411e+00,4.145098e+00,8.742359e+00,2.436402e+00,2.483921e+00,1.496569e+00,9.031859e+00,1.883046e+00,1.544741e+01,...,3.168970e+00,1.291218e+00,6.822439e+00,3.549938,9.198120e-01,1.672658e+00,3.239542e+00,0.310144,1.925763e+00,1.739389e+00
std,8.132649e-01,2.225036e+00,8.626621e-01,1.543441e+00,4.506138e-01,4.427150e-01,2.109786e+00,1.449542e+00,1.393466e+00,5.933834e-01,...,3.163604e+00,5.545506e-01,1.348700e+00,1.943431,1.591555e+00,3.779128e-01,1.221225e+00,0.693262,9.496402e-01,8.518204e-01
min,-9.996497e-07,-9.817614e-07,-6.475929e-07,-5.287068e-07,-9.055091e-07,-9.468765e-07,-7.783778e-07,-9.828757e-07,-9.875317e-07,-1.459062e-07,...,-9.998183e-07,-9.932534e-07,-9.978497e-07,0.019139,-9.994953e-07,-9.564174e-07,-9.223798e-07,0.000000,-9.901257e-07,-9.999134e-07
25%,1.346153e+00,6.575770e+00,4.068697e+00,8.394090e+00,2.340968e+00,2.376586e+00,2.653147e-01,8.813560e+00,1.050328e+00,1.539823e+01,...,1.169425e+00,1.052632e+00,6.519607e+00,2.571053,8.471320e-02,1.570974e+00,2.762497e+00,0.000000,1.449477e+00,1.463414e+00
50%,1.630686e+00,7.464411e+00,4.145098e+00,8.742359e+00,2.436402e+00,2.483921e+00,1.496569e+00,9.031859e+00,1.312910e+00,1.544741e+01,...,3.168970e+00,1.291218e+00,6.822439e+00,3.549938,9.198120e-01,1.672658e+00,3.239542e+00,0.000000,1.925763e+00,1.739389e+00
75%,1.630686e+00,7.551501e+00,4.340229e+00,8.924798e+00,2.484699e+00,2.528445e+00,1.496569e+00,9.302325e+00,2.100657e+00,1.559390e+01,...,3.168970e+00,1.291218e+00,6.999999e+00,3.549938,9.198120e-01,1.672658e+00,3.239542e+00,0.000000,1.925763e+00,1.739389e+00
max,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,2.000000e+01,1.853392e+01,2.000000e+01,...,2.000000e+01,1.039427e+01,2.000000e+01,19.686069,2.000000e+01,1.563161e+01,2.000000e+01,11.000000,2.000000e+01,2.000000e+01

# Run XgBoost